# 04 数组类型

### 二进制文件的读写

In [1]:
import numpy as np

In [ ]:
a = np.array([102,111,212], dtype=np.uint8)
a.tofile('foo.dat')

In [2]:
b = np.frombuffer(b'foo', dtype=np.uint8)
b

array([102, 111, 111], dtype=uint8)

In [ ]:
import os
os.remove('foo.dat')

### 获取ASC II码

In [ ]:
ord('f')  # 用 ord 函数来查看字符的ASCⅡ码值

In [ ]:
ord('S')

### 保证输入是数组

In [5]:
a = np.array([1, 2, 3, 4], dtype=np.int32)
a

array([1, 2, 3, 4], dtype=int32)

In [6]:
b = np.asarray(a, dtype=np.int32)
b

array([1, 2, 3, 4], dtype=int32)

In [7]:
b is a  # 这样做的目的是保证输入值是数组。如果a是数组时，不会产生新的对象（垃圾）

True