# 05 数组方法

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

### 求和

In [4]:
a.sum()

21

In [5]:
a.sum(axis=0)  # 其他方法类似，以下不举例了

array([5, 7, 9])

In [6]:
a.sum(axis=1)

array([ 6, 15])

### 求积

In [7]:
a.prod()

720

### 最大值最小值

In [9]:
a.max()

6

In [10]:
a.min()

1

### 最大最小值的位置

In [13]:
a.argmin()

0

In [14]:
a.argmax()

5

### 均值

In [16]:
a.mean()

3.5

In [18]:
np.average(a)

3.5

### 标准差

In [19]:
a.std()  # 标准差

1.707825127659933

In [20]:
a.var()  # 方差

2.9166666666666665

### clip方法

In [21]:
a.clip(3, 5)  # 将数值限制在某个范围

array([[3, 3, 3],
       [4, 5, 5]])

### ptp方法

In [22]:
a.ptp()  # 最大最小的差值

5

### round方法

In [25]:
a = np.array([1.35, 2.5, 1.5])  # 默认近似到整数，.5近似到偶数值
a.round()

array([ 1.,  2.,  2.])

In [26]:
a.round(decimals=1)  # 近似到一位小数

array([ 1.4,  2.5,  1.5])