# 06 数组排序

In [1]:
import numpy as np

### sort函数

In [7]:
names = np.array(['bob', 'sue', 'jan', 'ad'])
weights = np.array([20.8, 93.2, 53.4, 61.8])
weights.sort()  # 使用对象的方法 改变原来的数组
weights

array([ 20.8,  53.4,  61.8,  93.2])

In [9]:
weights = np.array([20.8, 93.2, 53.4, 61.8])
np.sort(weights)  # 使用顶级函数不改变原来的数组
weights

array([ 20.8,  93.2,  53.4,  61.8])

### argsort函数

In [11]:
ordered_indices = np.argsort(weights)
ordered_indices

array([0, 2, 3, 1])

In [12]:
weights.argsort()

array([0, 2, 3, 1])

In [15]:
weights

array([ 20.8,  93.2,  53.4,  61.8])

In [14]:
weights[ordered_indices]

array([ 20.8,  53.4,  61.8,  93.2])

In [20]:
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'],
      dtype='<U3')

In [23]:
weights[[0, 2, 3, 1]]

array([ 20.8,  53.4,  61.8,  93.2])

### 二维数组的排序

In [26]:
a = np.array([[.2, .1, .5], [.4, .8, .3], [.9, .6, .7]])
a

array([[ 0.2,  0.1,  0.5],
       [ 0.4,  0.8,  0.3],
       [ 0.9,  0.6,  0.7]])

In [28]:
np.sort(a)

array([[ 0.1,  0.2,  0.5],
       [ 0.3,  0.4,  0.8],
       [ 0.6,  0.7,  0.9]])

In [29]:
np.sort(a, axis=0)

array([[ 0.2,  0.1,  0.3],
       [ 0.4,  0.6,  0.5],
       [ 0.9,  0.8,  0.7]])

### searchsorted 函数

In [31]:
sorted_array = np.linspace(0, 1, 5)
sorted_array

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [34]:
values = np.array([.1, .8, .3, .12, .5, .25])
values

array([ 0.1 ,  0.8 ,  0.3 ,  0.12,  0.5 ,  0.25])

In [35]:
np.searchsorted(sorted_array, values)

# searchsorted 返回的值相当于保持第一个数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置：

# 例如 0.1 在 [0.0, 0.25) 之间，所以插入时应当放在第一个数组的索引 1 处，故第一个返回值为 1

array([1, 4, 2, 1, 2, 1])

### 例子

In [36]:
data = np.random.rand(100)
data.sort()  # 数据需要先经过排序
data

array([ 0.01119104,  0.01285866,  0.03202495,  0.04434481,  0.05757729,
        0.06625552,  0.06740823,  0.08657268,  0.10792882,  0.11831968,
        0.149694  ,  0.15737009,  0.16622169,  0.17173076,  0.17834448,
        0.18571489,  0.1887234 ,  0.19301845,  0.21123154,  0.22163723,
        0.22760531,  0.22919978,  0.23123018,  0.25419904,  0.27914547,
        0.28191398,  0.2845294 ,  0.28702823,  0.33875039,  0.34868272,
        0.35218831,  0.35372691,  0.38284549,  0.3835797 ,  0.38472875,
        0.39510092,  0.39977222,  0.40054079,  0.41766983,  0.42178345,
        0.43953176,  0.44175932,  0.44870079,  0.45143479,  0.46377431,
        0.4688973 ,  0.48339776,  0.51038328,  0.51804684,  0.5210138 ,
        0.52129882,  0.54563452,  0.5497229 ,  0.57304998,  0.59489115,
        0.60455266,  0.63061184,  0.63245245,  0.63518834,  0.64175315,
        0.6450372 ,  0.6466292 ,  0.6482023 ,  0.6538987 ,  0.67033352,
        0.67928169,  0.71151043,  0.7136783 ,  0.71864751,  0.72

In [37]:
bounds = .4, .6  # 指定的范围
bounds

(0.4, 0.6)

In [39]:
low_idx, high_idx = np.searchsorted(data, bounds)  # 放回指定范围的索引位置

In [40]:
low_idx  # 起始索引位置

37

In [41]:
high_idx  # 终止索引位置

55

In [42]:
data[low_idx:high_idx]  # 提取指定范围数据

array([ 0.40054079,  0.41766983,  0.42178345,  0.43953176,  0.44175932,
        0.44870079,  0.45143479,  0.46377431,  0.4688973 ,  0.48339776,
        0.51038328,  0.51804684,  0.5210138 ,  0.52129882,  0.54563452,
        0.5497229 ,  0.57304998,  0.59489115])