# 07 数组的shape

In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.shape = 2, 3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
a.reshape(3, 2)  # reshape方法不会改变原数组

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5]])

### 使用 newaxis 增加数组维数

In [6]:
a = np.arange(3)
np.shape(a)

(3,)

In [7]:
y = a[np.newaxis, :]
np.shape(y)

(1, 3)

In [8]:
y

array([[0, 1, 2]])

In [9]:
a

array([0, 1, 2])

In [10]:
y = a[np.newaxis, np.newaxis, :]  # 插入多个维度
np.shape(y)

(1, 1, 3)

In [11]:
y

array([[[0, 1, 2]]])

### squeeze 方法去除多余的轴

In [12]:
a = np.arange(6)
a.shape = (2, 1, 3)
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [13]:
b = a.squeeze()  # squeeze 返回一个将所有长度为1的维度去除的新数组
b.shape

(2, 3)

### 数组转置

In [14]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
b.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [16]:
a.T  # 缩写

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

### 数组连接

In [17]:
x = np.array([[0, 1, 2], [10, 11, 12]])
y = np.array([[50, 51, 52], [60, 61, 62]])

In [18]:
z = np.concatenate((x, y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [19]:
z = np.concatenate((x, y), axis=1)  # 沿着另一维连接 列
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [20]:
z = np.array((x, y))
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])

### 另一种表达方式

In [21]:
np.vstack((x, y)).shape

(4, 3)

In [22]:
np.vstack((x, y))

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [23]:
np.hstack((x, y))

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [24]:
np.dstack((x, y))

array([[[ 0, 50],
        [ 1, 51],
        [ 2, 52]],

       [[10, 60],
        [11, 61],
        [12, 62]]])

### Flatten 数组

In [25]:
a = np.array([[0, 1], [2, 3]])
b = a.flatten()
b

array([0, 1, 2, 3])

### flat 属性

In [26]:
a.flat  # 返回了所有元组组成的一个迭代器

In [28]:
for item in a.flat:
    print(item)

0
1
2
3


In [29]:
a

array([[0, 1],
       [2, 3]])

In [30]:
a.flat[:]

array([0, 1, 2, 3])

### ravel 方法

In [32]:
a = np.array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])